---
intitle: "DS 2003 Midterm Project - Group 5"
output: html_document
date: "2024-02-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("tidyverse")
```

```{r}
# Please Note: after downloading the data, rename it to "LA_data.csv" (and place it in the same directory)
# The .gitignore file ignores this name to prevent the data from getting committed to GitHub
data <- read.csv("LA_data.csv")
```

```{r}
data
```

# Data Cleaning

```{r}

# Remove crimes with no location info
data <- data %>%
  filter(LAT != 0.0 & LON != 0.0) %>%
  mutate(index = row_number()) %>%
  select(index, everything())

# Convert to a proper data time format
data$Date.Rptd <- as.Date(data$Date.Rptd, format = "%m/%d/%Y %I:%M:%S %p")


# Filter for dates within the last year from 02/22/2024
# data <- data[data$Date.Rptd >= as.Date("2023-02-22") & data$Date.Rptd <= as.Date("2024-02-22"), ]

```


```{r}
data
```


#### Map crime types to broader categories

```{r}
# Map the 139 crime categories to broader categories
crime_mappings <- c(
  "VEHICLE - STOLEN" = "Theft and Property Crimes",
  "BURGLARY FROM VEHICLE" = "Theft and Property Crimes",
  "BIKE - STOLEN" = "Theft and Property Crimes",
  "SHOPLIFTING-GRAND THEFT ($950.01 & OVER)" = "Theft and Property Crimes",
  "THEFT OF IDENTITY" = "Theft and Property Crimes",
  "BATTERY - SIMPLE ASSAULT" = "Assault and Violence",
  "SODOMY/SEXUAL CONTACT B/W PENIS OF ONE PERS TO ANUS OTH" = "Sex Crimes",
  "CRM AGNST CHLD (13 OR UNDER) (14-15 & SUSP 10 YRS OLDER)" = "Sex Crimes",
  "SEX,UNLAWFUL(INC MUTUAL CONSENT, PENETRATION W/ FRGN OBJ" = "Sex Crimes",
  "ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT" = "Assault and Violence",
  "LETTERS, LEWD  -  TELEPHONE CALLS, LEWD" = "Sex Crimes",
  "THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LIVESTK,PROD" = "Theft and Property Crimes",
  "RAPE, FORCIBLE" = "Sex Crimes",
  "CRIMINAL THREATS - NO WEAPON DISPLAYED" = "Theft and Property Crimes",
  "EMBEZZLEMENT, GRAND THEFT ($950.01 & OVER)" = "Fraud and White-Collar Crimes",
  "THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER)" = "Traffic and Vehicle-Related Crimes",
  "CHILD ANNOYING (17YRS & UNDER)" = "Sex Crimes",
  "BURGLARY" = "Theft and Property Crimes",
  "CONTEMPT OF COURT" = "Miscellaneous Crimes",
  "THEFT PLAIN - PETTY ($950 & UNDER)" = "Theft and Property Crimes",
  "INTIMATE PARTNER - SIMPLE ASSAULT" = "Assault and Violence",
  "LEWD CONDUCT" = "Sex Crimes",
  "THEFT PLAIN - ATTEMPT" = "Theft and Property Crimes",
  "THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND OVER)" = "Theft and Property Crimes",
  "OTHER MISCELLANEOUS CRIME" = "Miscellaneous Crimes",
  "ROBBERY" = "Theft and Property Crimes",
  "BUNCO, GRAND THEFT" = "Theft and Property Crimes",
  "SEXUAL PENETRATION W/FOREIGN OBJECT" = "Sex Crimes",
  "BATTERY WITH SEXUAL CONTACT" = "Sex Crimes",
  "INTIMATE PARTNER - AGGRAVATED ASSAULT" = "Assault and Violence",
  "ORAL COPULATION" = "Sex Crimes",
  "UNAUTHORIZED COMPUTER ACCESS" = "Fraud and White-Collar Crimes",
  "VIOLATION OF RESTRAINING ORDER" = "Miscellaneous Crimes",
  "SHOPLIFTING - PETTY THEFT ($950 & UNDER)" = "Theft and Property Crimes",
  "VANDALISM - FELONY ($400 & OVER, ALL CHURCH VANDALISMS)" = "Theft and Property Crimes",
  "BRANDISH WEAPON" = "Assault and Violence",
  "DOCUMENT FORGERY / STOLEN FELONY" = "Fraud and White-Collar Crimes",
  "SEX OFFENDER REGISTRANT OUT OF COMPLIANCE" = "Miscellaneous Crimes",
  "VANDALISM - MISDEAMEANOR ($399 OR UNDER)" = "Theft and Property Crimes",
  "CHILD ABUSE (PHYSICAL) - SIMPLE ASSAULT" = "Assault and Violence",
  "CREDIT CARDS, FRAUD USE ($950.01 & OVER)" = "Fraud and White-Collar Crimes",
  "THREATENING PHONE CALLS/LETTERS" = "Fraud and White-Collar Crimes",
  "EXTORTION" = "Fraud and White-Collar Crimes",
  "OTHER ASSAULT" = "Assault and Violence",
  "PICKPOCKET" = "Theft and Property Crimes",
  "DISTURBING THE PEACE" = "Assault and Violence",
  "BUNCO, ATTEMPT" = "Fraud and White-Collar Crimes",
  "HUMAN TRAFFICKING - INVOLUNTARY SERVITUDE" = "Sex Crimes",
  "PEEPING TOM" = "Sex Crimes",
  "VIOLATION OF COURT ORDER" = "Miscellaneous Crimes",
  "FALSE POLICE REPORT" = "Fraud and White-Collar Crimes",
  "CONTRIBUTING" = "Miscellaneous Crimes",
  "FALSE IMPRISONMENT" = "Fraud and White-Collar Crimes",
  "CHILD ABUSE (PHYSICAL) - AGGRAVATED ASSAULT" = "Assault and Violence",
  "ATTEMPTED ROBBERY" = "Theft and Property Crimes",
  "CREDIT CARDS, FRAUD USE ($950 & UNDER" = "Fraud and White-Collar Crimes",
  "CHILD STEALING" = "Assault and Violence",
  "LEWD/LASCIVIOUS ACTS WITH CHILD" = "Sex Crimes",
  "EMBEZZLEMENT, PETTY THEFT ($950 & UNDER)" = "Fraud and White-Collar Crimes",
  "CHILD NEGLECT (SEE 300 W.I.C.)" = "Assault and Violence",
  "STALKING" = "Assault and Violence",
  "DISHONEST EMPLOYEE - GRAND THEFT" = "Fraud and White-Collar Crimes",
  "TRESPASSING" = "Miscellaneous Crimes",
  "BURGLARY, ATTEMPTED" = "Theft and Property Crimes",
  "RAPE, ATTEMPTED" = "Sex Crimes",
  "DISCHARGE FIREARMS/SHOTS FIRED" = "Assault and Violence",
  "ARSON" = "Theft and Property Crimes",
  "HUMAN TRAFFICKING - COMMERCIAL SEX ACTS" = "Sex Crimes",
  "VEHICLE - ATTEMPT STOLEN" = "Traffic and Vehicle-Related Crimes",
  "PANDERING" = "Sex Crimes",
  "FIREARMS RESTRAINING ORDER (FIREARMS RO)" = "Assault and Violence",
  "RESISTING ARREST" = "Assault and Violence",
  "BURGLARY FROM VEHICLE, ATTEMPTED" = "Traffic and Vehicle-Related Crimes",
  "THEFT, PERSON" = "Theft and Property Crimes",
  "BATTERY POLICE (SIMPLE)" = "Assault and Violence",
  "VEHICLE, STOLEN - OTHER (MOTORIZED SCOOTERS, BIKES, ETC)" = "Traffic and Vehicle-Related Crimes",
  "INDECENT EXPOSURE" = "Sex Crimes",
  "THEFT FROM PERSON - ATTEMPT" = "Theft and Property Crimes",
  "FAILURE TO YIELD" = "Traffic and Vehicle-Related Crimes",
  "BOMB SCARE" = "Assault and Violence",
  "ASSAULT WITH DEADLY WEAPON ON POLICE OFFICER" = "Assault and Violence",
  "PIMPING" = "Sex Crimes",
  "BUNCO, PETTY THEFT" = "Fraud and White-Collar Crimes",
  "SHOTS FIRED AT INHABITED DWELLING" = "Assault and Violence",
  "DEFRAUDING INNKEEPER/THEFT OF SERVICES, $950 & UNDER" = "Fraud and White-Collar Crimes",
  "KIDNAPPING - GRAND ATTEMPT" = "Assault and Violence",
  "SHOTS FIRED AT MOVING VEHICLE, TRAIN OR AIRCRAFT" = "Traffic and Vehicle-Related Crimes",
  "TILL TAP - GRAND THEFT ($950.01 & OVER)" = "Theft and Property Crimes",
  "VIOLATION OF TEMPORARY RESTRAINING ORDER" = "Miscellaneous Crimes",
  "THROWING OBJECT AT MOVING VEHICLE" = "Traffic and Vehicle-Related Crimes",
  "DOCUMENT WORTHLESS ($200.01 & OVER)" = "Fraud and White-Collar Crimes",
  "KIDNAPPING" = "Assault and Violence",
  "CRIMINAL HOMICIDE" = "Assault and Violence",
  "PURSE SNATCHING" = "Theft and Property Crimes",
  "THEFT FROM MOTOR VEHICLE - ATTEMPT" = "Traffic and Vehicle-Related Crimes",
  "DISHONEST EMPLOYEE - PETTY THEFT" = "Fraud and White-Collar Crimes",
  "CHILD PORNOGRAPHY" = "Sex Crimes",
  "WEAPONS POSSESSION/BOMBING" = "Assault and Violence",
  "DRIVING WITHOUT OWNER CONSENT (DWOC)" = "Traffic and Vehicle-Related Crimes",
  "REPLICA FIREARMS(SALE,DISPLAY,MANUFACTURE OR DISTRIBUTE)" = "Fraud and White-Collar Crimes",
  "LYNCHING" = "Assault and Violence",
  "RECKLESS DRIVING" = "Traffic and Vehicle-Related Crimes",
  "SHOPLIFTING - ATTEMPT" = "Theft and Property Crimes",
  "COUNTERFEIT" = "Fraud and White-Collar Crimes",
  "DEFRAUDING INNKEEPER/THEFT OF SERVICES, OVER $950.01" = "Fraud and White-Collar Crimes",
  "BATTERY ON A FIREFIGHTER" = "Assault and Violence",
  "CRUELTY TO ANIMALS" = "Assault and Violence",
  "BOAT - STOLEN" = "Traffic and Vehicle-Related Crimes",
  "ILLEGAL DUMPING" = "Miscellaneous Crimes",
  "PROWLER" = "Theft and Property Crimes",
  "DRUGS, TO A MINOR" = "Miscellaneous Crimes",
  "THEFT, COIN MACHINE - PETTY ($950 & UNDER)" = "Theft and Property Crimes",
  "DOCUMENT WORTHLESS ($200 & UNDER)" = "Fraud and White-Collar Crimes",
  "MANSLAUGHTER, NEGLIGENT" = "Assault and Violence",
  "PETTY THEFT - AUTO REPAIR" = "Theft and Property Crimes",
  "THEFT, COIN MACHINE - ATTEMPT" = "Theft and Property Crimes",
  "TILL TAP - PETTY ($950 & UNDER)" = "Theft and Property Crimes",
  "PURSE SNATCHING - ATTEMPT" = "Theft and Property Crimes",
  "LYNCHING - ATTEMPTED" = "Assault and Violence",
  "BIKE - ATTEMPTED STOLEN" = "Theft and Property Crimes",
  "GRAND THEFT / AUTO REPAIR" = "Traffic and Vehicle-Related Crimes",
  "CONSPIRACY" = "Fraud and White-Collar Crimes",
  "BRIBERY" = "Fraud and White-Collar Crimes",
  "GRAND THEFT / INSURANCE FRAUD" = "Fraud and White-Collar Crimes",
  "DRUNK ROLL" = "Theft and Property Crimes",
  "CHILD ABANDONMENT" = "Assault and Violence",
  "THEFT, COIN MACHINE - GRAND ($950.01 & OVER)" = "Theft and Property Crimes",
  "DISRUPT SCHOOL" = "Miscellaneous Crimes",
  "PICKPOCKET, ATTEMPT" = "Theft and Property Crimes",
  "TELEPHONE PROPERTY - DAMAGE" = "Theft and Property Crimes",
  "BEASTIALITY, CRIME AGAINST NATURE SEXUAL ASSLT WITH ANIM" = "Sex Crimes",
  "BIGAMY" = "Fraud and White-Collar Crimes",
  "FAILURE TO DISPERSE" = "Miscellaneous Crimes",
  "FIREARMS EMERGENCY PROTECTIVE ORDER (FIREARMS EPO)" = "Miscellaneous Crimes",
  "INCEST (SEXUAL ACTS BETWEEN BLOOD RELATIVES)" = "Sex Crimes",
  "BLOCKING DOOR INDUCTION CENTER" = "Miscellaneous Crimes",
  "INCITING A RIOT" = "Miscellaneous Crimes",
  "DISHONEST EMPLOYEE ATTEMPTED THEFT" = "Fraud and White-Collar Crimes",
  "TRAIN WRECKING" = "Miscellaneous Crimes"
  )

data <- data %>%
  mutate(Crime_Broad_Category = crime_mappings[Crm.Cd.Desc])

table(data$Crime_Broad_Category)
```

# Question 1

```{r}
table(data$Vict.Descent)
```


```{r}

# Divide ages into age groups of 10 years
data_valid_ages <- data[data$Vict.Age >= 1 & data$Vict.Age <= 99, ]
data_valid_ages$Age_Group <- cut(
  as.numeric(data_valid_ages$Vict.Age), 
  breaks = seq(0, 100, by = 10), 
  labels = c("0-9", "10-19", "20-29", "30-39", "40-49", "50-59", "60-69", "70-79", "80-89", "90+")
)

data_valid_ages$Age_Group_2 <- cut(
  as.numeric(data_valid_ages$Vict.Age), 
  breaks = seq(0, 100, by = 20), 
  labels = c("0-19", "20-39", "40-59", "60-79", "80+")
)

# Clean up the victim sex column
data_valid_ages <- data_valid_ages[data_valid_ages$Vict.Sex == "M" | data_valid_ages$Vict.Sex == "F", ]
data_valid_ages$Vict.Sex <- factor(data_valid_ages$Vict.Sex, labels = c("Male", "Female"))

# Aggregate the victim race column
data_valid_ages <- data_valid_ages[data_valid_ages$Vict.Descent != "-" & data_valid_ages$Vict.Descent != "", ]

race_mappings <- c(
  "A" = "Asian",
  "B" = "Black",
  "C" = "Asian",
  "D" = "Asian",
  "F" = "Asian",
  "G" = "Native Hawaiian/Pacific Islander",
  "H" = "Hispanic/Latino",
  "I" = "American Indian/Alaska Native",
  "J" = "Asian",
  "K" = "Asian",
  "L" = "Hispanic/Latino",
  "O" = "Others",
  "P" = "Native Hawaiian/Pacific Islander",
  "S" = "Native Hawaiian/Pacific Islander",
  "U" = "Native Hawaiian/Pacific Islander",
  "V" = "Asian",
  "W" = "White",
  "X" = "Others",
  "Z" = "Asian"
)

race_colors <- c(
  "Asian" = "#fdbf6f",
  "Black" = "#e31a1c",
  "Hispanic/Latino" = "#33a02c",
  "White" = "#1f78b4",
  "Native Hawaiian/Pacific Islander" = "#a6cee3",
  "American Indian/Alaska Native" = "#ff7f00",
  "Others" = "#6a3d9a"
)

data_valid_ages <- data_valid_ages %>%
  mutate(Race_Broad_Category = race_mappings[Vict.Descent])
```

```{r fig.width = 10}

ggplot(data_valid_ages, aes(x = Age_Group, fill = Race_Broad_Category)) +
  geom_bar(position = "dodge") +
  facet_wrap(~ Vict.Sex, nrow = 1) +
  labs(x = "Age Group", y = "Number of Crimes", fill = "Race") +
  labs(
    title = "Number of Crimes in Los Angeles, CA",
    subtitle = "By Victim Sex, Age, and Descent",
    caption = "Data from the LAPD"
  ) +
  scale_fill_manual(values = race_colors) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

# Question 2

```{r fig.width = 10}
# Find the number of crimes in each category for each area of LA
crime_counts_by_area <- data %>%
  group_by(AREA.NAME, Crime_Broad_Category) %>%
  summarise(Count = n())

# Get the total crimes for each area
area_totals <- data %>%
  group_by(AREA.NAME) %>%
  summarise(Total_Crimes = n())

# Merge the total crimes and crimes by type data frames
crime_conuts_by_area_with_totals <- merge(crime_counts_by_area, area_totals, by = "AREA.NAME")

# Normalize the crimes by the population of each area (crimes per 1000 people)
population_by_lapd_juris <- read.csv("police_la_juris_pop.csv")
crime_conuts_by_area_with_totals <- merge(crime_conuts_by_area_with_totals, population_by_lapd_juris, by = "AREA.NAME")
crime_conuts_by_area_with_totals$Crimes_Per_1000_People <- (crime_conuts_by_area_with_totals$Count / crime_conuts_by_area_with_totals$Population) * 1000
crime_conuts_by_area_with_totals$Total_Crimes_Per_1000_People <- (crime_conuts_by_area_with_totals$Total_Crimes / crime_conuts_by_area_with_totals$Population) * 1000

# Make a bar chart which shows the 3 variables
ggplot(crime_conuts_by_area_with_totals, aes(x = Crimes_Per_1000_People, y = reorder(AREA.NAME, Total_Crimes_Per_1000_People), fill = Crime_Broad_Category)) +
  geom_bar(stat = "identity") +
  labs(x = "Count", y = "Area") +
  labs(
    title = "Number of Crimes in Los Angeles (2020 - Present)",
    subtitle = "Per 1,000 People by Area and Crime Type",
    x = "Number of Crimes Per 1,000 People",
    y = "Area of City",
    fill = 'Crime Type',
    caption = "Data from the LAPD"
  ) +
  theme_minimal()
```

# Question 3

```{r}
table(data$Weapon.Desc)
```
```{r}
# install.packages("treemapify")
```


```{r fig.width = 10}
# Load necessary libraries
library(tidyverse)
library(treemapify)

# Parse the weapon descriptions and create subcategories
data_weapon_subcategories <- data %>%
  mutate(Weapon_Subcategory = case_when(
    grepl("KNIFE", Weapon.Desc) ~ "Knife",
    grepl("GUN|REVOLVER|RIFLE|SHOTGUN|FIREARM|ASSAULT|UZI|SHOTGUN|PISTOL|SEMIAUTOMATIC", Weapon.Desc) ~ "Firearm",
    grepl("AXE|MACHETE|SWORD|BLADE|BOTTLE|CLEAVER|RAZOR|SYRINGE|SCISSORS|CUTTING|SCREWDRIVER|GLASS", Weapon.Desc) ~ "Sharp Weapon",
    grepl("BAT|BOARD|HAMMER|STICK|CHAIN|BLUNT|STICK|CONCRETE|PIPE|ROCK|TIRE IRON|BRICK", Weapon.Desc) ~ "Blunt Object",
    grepl("CHEMICAL|POISON|MACE|SPRAY|CAUSTIC", Weapon.Desc) ~ "Chemical/Pepper Spray",
    grepl("BOMB|EXPLOSIVE|EXPLOXIVE", Weapon.Desc) ~ "Explosive",
    grepl("VEHICLE", Weapon.Desc) ~ "Vehicle",
    grepl("BODILY|FEET|FIST", Weapon.Desc) ~ "Bodily Force",
    grepl("UNKNOWN WEAPON/OTHER WEAPON", Weapon.Desc) ~ "Unknown Weapon",
    grepl("VERBAL THREAT", Weapon.Desc) ~ "Verbal Threat",
    grepl("FIRE|SCALDING", Weapon.Desc) ~ "Fire/Heat",
    grepl("ANIMAL", Weapon.Desc) ~ "Animal",
    TRUE ~ "Other"
  ))

# Count the occurrences of each subcategory
weapon_subcategory_counts <- data_weapon_subcategories %>%
  filter(Weapon_Subcategory != "Other") %>%
  count(Weapon_Subcategory) %>%
  arrange(desc(n))

# Plot the treemap
ggplot(weapon_subcategory_counts, aes(area = n, fill = Weapon_Subcategory, label = paste0(Weapon_Subcategory, ": ", n))) +
  geom_treemap() +
  geom_treemap_text(place = "centre", colour = "white", alpha = 1, reflow = T) +
  scale_fill_viridis_d(option = "A") +
  # theme(legend.position = "none") +
  labs(
    title = "Types of Weapons Used",
    subtitle = "For Violent Crimes in Los Angeles, CA (2020-present)",
    fill = "Weapon Type",
    caption = "Data source: LAPD"
  )

```

# Apppendix

## Question 1

```{r}
crime_trends <- data_valid_ages %>%
  mutate(Date.Rptd = floor_date(Date.Rptd, unit = "month")) %>%
  group_by(Date.Rptd, Vict.Sex, Race_Broad_Category, Age_Group_2) %>%
  summarise(Num_Crimes = n()) %>%
  ungroup()
crime_trends
```

```{r fig.width = 14}

ggplot(crime_trends, aes(x = Date.Rptd, y = Num_Crimes, color = Race_Broad_Category, linetype = Vict.Sex)) +
  geom_line() +
  facet_grid(rows = vars(Age_Group_2)) +
  labs(
    x = "Month",
    y = "Number of Crimes",
    color = "Victim Race",
    linetype = "Victim Sex",
    title = "Monthly Crime Trends by Age Group, Sex, and Race",
    subtitle = "Number of Crimes Reported by Month for Each Demographic Group",
    caption = "Data from the LAPD"
  ) +
  
  scale_y_continuous(
    sec.axis = sec_axis(~ ., name = "Age Group", breaks = NULL)
  ) +
  scale_x_date(date_breaks = "3 months", date_labels = "%b %Y") + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  scale_color_manual(values = race_colors)
```

## Question 2

```{r fig.width = 14}

race_colors <- c(
  "Asian" = "#fdbf6f",
  "Black" = "#e31a1c",
  "Hispanic/Latino" = "#33a02c",
  "White" = "#1f78b4",
  "Native Hawaiian/Pacific Islander" = "#a6cee3",
  "American Indian/Alaska Native" = "#ff7f00",
  "Others" = "#6a3d9a"
)

ggplot() +
  geom_point(data = data_valid_ages, aes(x = LON, y = LAT, color = Race_Broad_Category), alpha = 0.5, size = 1) +
  labs(x = 'Longitude', y = 'Latitude', title = 'LA Crime Data') +
  scale_fill_manual(values = race_colors) +
  scale_color_manual(values = race_colors) +
  labs(
    title = "Distribution of Crimes in Los Angeles, CA",
    subtitle = "Geographic Distribution by Race of Victim",
    caption = "Data from the LAPD",
    color = "Victim Race"
  ) +
  theme_minimal()
```

```{r}
library(sf)

LA <- st_read("County_Boundary.shp",
              stringsAsFactors = FALSE)
LA_city <- filter(LA, CITY_LABEL == "Los Angeles")


ggplot() +
  geom_sf(data=LA_city) +
  geom_hex(data=data,
           mapping = aes(x=LON, y=LAT), bins=11, color="black")+
  scale_fill_fermenter(n.breaks=10,palette = "RdYlBu")+
  labs (
    title = "Number of Crimes in Los Angeles, CA",
    subtitle = "Hexagons denote approximate location",
    caption = "Data from the LAPD",
    color = "Crimes"
  ) +
  theme_void() +
  theme(
    plot.subtitle = element_text(margin = margin(b = 10))
  )
```

## Work in progress code

```{r}
library(sf)
LA <- st_read("County_Boundary.shp",
              stringsAsFactors = FALSE)
```



```{r fig.width = 14}

ggplot(data_valid_ages, aes(x = LON, y = LAT, color = Race_Broad_Category)) +
  
  geom_point(alpha = 0.5, size = 1) +
  labs(x = 'Longitude', y = 'Latitude', title = 'LA Crime Data') +
  scale_fill_manual(values = race_colors) +
  theme_minimal()
```

```{r fig.width = 14}
ggplot(data, aes(x = LON, y = LAT, color = Crime_Broad_Category)) +
  geom_point(size=0.5) +
  labs(x = 'Longitude', y = 'Latitude', title = 'LA Crime Data') +
  theme_minimal()
```

```{r fig.width = 10}

# Find the number of crimes in each category for each area of LA
crime_counts_by_area <- data %>%
  group_by(AREA.NAME, Crime_Broad_Category) %>%
  summarise(Count = n())

# Get the total crimes for each area
area_totals <- data %>%
  group_by(AREA.NAME) %>%
  summarise(Total_Crimes = n())

# Merge the total crimes and crimes by type data frames
crime_conuts_by_area_with_totals <- merge(crime_counts_by_area, area_totals, by = "AREA.NAME")

# Normalize the crimes by the population of each area (crimes per 1000 people)
population_by_lapd_juris <- read.csv("police_la_juris_pop.csv")
crime_conuts_by_area_with_totals <- merge(crime_conuts_by_area_with_totals, population_by_lapd_juris, by = "AREA.NAME")
crime_conuts_by_area_with_totals$Crimes_Per_1000_People <- (crime_conuts_by_area_with_totals$Count / crime_conuts_by_area_with_totals$Population) * 1000

# Make a bar chart which shows the 3 variables
ggplot(crime_conuts_by_area_with_totals, aes(x = Count, y = reorder(AREA.NAME, Total_Crimes), fill = Crime_Broad_Category)) +
  geom_bar(stat = "identity") +
  labs(x = "Count", y = "Area") +
  labs(
    title = "Number of Crimes in Los Angeles",
    x = "Number of Reports",
    y = "Area of City",
    fill = 'Crime Type',
    caption = "Data from the LAPD"
  ) +
  theme_minimal()

```

```{r}
crime_trends <- data_valid_ages %>%
  group_by(Date.Rptd, Vict.Sex, Vict.Descent, Vict.Age) %>%
  summarise(Num_Crimes = n()) %>%
  ungroup()
crime_trends
```

```{r}
crime_trends <- data_valid_ages %>%
  mutate(Date.Rptd = floor_date(Date.Rptd, unit = "month")) %>%
  group_by(Date.Rptd, Vict.Sex, Race_Broad_Category, Age_Group_2) %>%
  summarise(Num_Crimes = n()) %>%
  ungroup()
crime_trends
```

```{r fig.width = 14}

ggplot(crime_trends, aes(x = Date.Rptd, y = Num_Crimes, color = Race_Broad_Category, linetype = Vict.Sex)) +
  geom_line() +
  facet_grid(rows = vars(Age_Group_2)) +
  labs(
    x = "Month",
    y = "Number of Crimes",
    color = "Victim Race",
    linetype = "Victim Sex",
    title = "Monthly Crime Trends by Age Group, Sex, and Race",
    subtitle = "Number of Crimes Reported by Month for Each Demographic Group",
    caption = "Data from the LAPD"
  ) +
  
  scale_y_continuous(
    sec.axis = sec_axis(~ ., name = "Age Group", breaks = NULL)
  ) +
  scale_x_date(date_breaks = "3 months", date_labels = "%b %Y") + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  scale_color_manual(values = race_colors)
```



```{r}
# Assuming you have a dataframe named 'data_valid_ages' with columns for date, Vict.Sex, Vict.Descent, and Vict.Age

# Convert date column to Date type
# data_valid_ages$Date <- as.Date(data_valid_ages$Date.Rptd, format = "%m/%d/%Y")

# Aggregate data by date, Vict.Sex, Vict.Descent, and Vict.Age
crime_trends <- data_valid_ages %>%
  group_by(Date.Rptd, Vict.Sex, Race_Broad_Category, Vict.Age) %>%
  summarise(Num_Crimes = n()) %>%
  ungroup()

# Plot the trends
ggplot(crime_trends, aes(x = Date.Rptd, y = Num_Crimes, color = Vict.Sex, linetype = Race_Broad_Category)) +
  geom_line() +
  facet_grid(rows = vars(Vict.Age)) +
  labs(
    x = "Date",
    y = "Number of Crimes",
    color = "Sex",
    linetype = "Race",
    title = "Crime Trends Over Time by Age Group, Sex, and Race",
    subtitle = "Number of Crimes Reported by Date for Each Demographic Group",
    caption = "Data from the LAPD"
  ) +
  theme_minimal()

```

